name: Tests

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  tests:
    name: "PHP Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "xdebug"
          php-version: "7.4"
          ini-values: zend.assertions=1
          tools: composer:v2

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-composer-"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest --ignore-platform-reqs"

      - name: Build API for testing
        id: generated-data
        run: |
          composer run-script api-build

      - name: "Run CI"
        run: "composer run-script ci"

      - name: Convert SVG to PNG
        continue-on-error: true
        env:
          WINDOW_SIZE: ${{ steps.generated-data.outputs.WINDOW_SIZE }}
        run: composer run-script convert-svg

      - name: Post current raid grahpic
        uses: edunad/actions-image@v1.0.1
        with:
          path: './public/api/graphics/English/*.png'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: 'This would be the new Raid Image'