name: page
on:
  push:
    branches:
      - main
  schedule:
    # At minute 25 past every 6th hour.
    - cron:  '25 */6 * * *'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.4"
          ini-values: zend.assertions=1
          tools: composer:v2

      - uses: actions/cache@v2
        with:
          path: data/tmp
          key: download-tmp-${{ hashFiles('data/tmp/hashes.json') }}

      - uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: "Install dependencies"
        run: composer install --no-interaction --no-progress --no-suggest --ignore-platform-reqs

      - name: Generate Data
        run: composer run-script build-api
        
      - name: "Test"
        continue-on-error: true
        run: |
          ls public/api/graphics/German/

      - name: Convert SVG to PNG
        uses: swinton/screenshot-website@v1.x
        continue-on-error: true
        with:
          source: public/api/graphics/German/raidlist.svg
          destination: public/api/graphics/German/raidlist.png
          width: 975
          height: 1260
          defaultBackground: false
          timeout: 30

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
