name: page
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # At minute 25 past every 6th hour.
    - cron:  '25 */6 * * *'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.4"
          ini-values: zend.assertions=1
          tools: composer:v2

      - uses: actions/cache@v2
        with:
          path: data/tmp
          key: download-tmp-${{ hashFiles('data/tmp/hashes.json') }}

      - uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: "Install dependencies"
        run: composer install --no-interaction --no-progress --no-suggest --ignore-platform-reqs

      - name: Generate Data
        run: composer run-script build-api

      - name: Convert SVG to PNG
        continue-on-error: true
        run: composer run-script convert-svg

      - name: Post current raid grahpic
        uses: edunad/actions-image@v1.0.1
        with:
          path: './public/api/graphics/German/*.png'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: 'This would be the new Raid Image'

      - name: Deploy to GitHub Pages
        if: ${{ success() && github.event_name != 'pull_request'}}
        uses: crazy-max/ghaction-github-pages@v2
        with:
          keep_history: true
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}