name: page
on:
  workflow_dispatch:
    inputs:
      forceCacheUpdate:
        description: 'Force cache update?'
        required: true
        default: 'true or false'

  pull_request:
  push:
    branches:
      - main
  schedule:
    # At minute 25 past every 2 hours.
    - cron:  '25 */2 * * *'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.4"
          ini-values: zend.assertions=1
          tools: composer:v2

      - uses: actions/cache@v2
        if: ${{ ! github.event.inputs.forceCacheUpdate }}
        with:
          path: data/tmp
          key: download-data-tmp-${{ github.run_id }}
          restore-keys: |
            download-data-tmp-

      - uses: actions/cache@v2
        with:
          path: |
            vendor/
            **/composer.lock
          key: composer-${{ hashFiles('**/composer.lock') }}


      - name: "Install dependencies"
        run: composer install --no-interaction --no-progress --no-suggest --ignore-platform-reqs

      - name: Generate Data
        id: generated-data
        run: composer run-script api-build

      - name: Convert SVG to PNG
        if: ${{ steps.generated-data.outputs.HAS_CHANGES || github.event.inputs.forceCacheUpdate }}
        continue-on-error: true
        run: composer run-script convert-svg

      - name: Post current raid grahpic
        if: ${{ (steps.generated-data.outputs.HAS_CHANGES || github.event.inputs.forceCacheUpdate) && github.event_name == 'pull_request' }}
        uses: edunad/actions-image@v1.0.1
        with:
          path: './public/api/graphics/German/*.png'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: 'This would be the new Raid Image'

      - name: Deploy to GitHub Pages
        if: ${{ (steps.generated-data.outputs.HAS_CHANGES || github.event.inputs.forceCacheUpdate) && github.event_name != 'pull_request'}}
        uses: crazy-max/ghaction-github-pages@v2
        with:
          keep_history: true
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
