name: page
on:
  workflow_dispatch:
    inputs:
      forceCacheUpdate:
        description: 'Force cache update?'
        required: false
        default: 'true or false'

  push:
    branches:
      - main

  schedule:
    # At minute 25 past every 2 hours.
    - cron:  '25 */2 * * *'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.4"
          ini-values: zend.assertions=1
          tools: composer:v2

      - uses: actions/cache@v2
        with:
          path: data/tmp
          key: download-data-tmp-${{ github.run_id }}
          restore-keys: |
            download-data-tmp-

      - uses: actions/cache@v2
        with:
          path: |
            vendor/
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: "Force cache update"
        if: ${{ github.event.inputs.forceCacheUpdate }}
        run: rm -rf data/tmp/*

      - name: "Install dependencies"
        run: composer install --no-interaction --no-progress --no-suggest --ignore-platform-reqs

      - name: Generate Data
        id: generated-data
        run: |
          composer run-script api-build

      - name: Debug HAS-CHANGES
        if: ${{ steps.generated-data.outputs.CACHE_STATUS == 'HAS_CHANGES' }}
        run: echo "${{ toJson(steps.generated-data.outputs) }}"

      - name: Debug HAS NO CHANGES
        if: ${{ steps.generated-data.outputs.CACHE_STATUS != 'HAS_CHANGES' }}
        run: echo "${{ toJson(steps.generated-data.outputs) }}"

      - name: Convert SVG to PNG
        if: ${{ steps.generated-data.outputs.CACHE_STATUS == 'HAS_CHANGES' }}
        continue-on-error: true
        env:
          WINDOW_SIZE: ${{ steps.generated-data.outputs.WINDOW_SIZE }}
        run: composer run-script convert-svg

      - name: Deploy to GitHub Pages
        if: ${{ (steps.generated-data.outputs.CACHE_STATUS == 'HAS_CHANGES') && github.event_name != 'pull_request'}}
        uses: crazy-max/ghaction-github-pages@v2
        with:
          keep_history: true
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
